export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const CHANGE_CART_ITEM_QUANTITY = 'CHANGE_CART_ITEM_QUANTITY';
export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const REPLACE_CART_ITEMS = 'REPLACE_CART_ITEMS';